version: 2.1

executors:
  openjdk8:
    docker:
      - image: maven:3.6-jdk-8

jobs:
  first:
    executor: openjdk8
    steps:
      - run: echo "first job"
  second:
    executor: openjdk8
    steps:
      - run: echo "second job"

workflows:
  welcome:
    jobs:
      - first
      - second
