version: 2.1

executors:
  openjdk8:
    docker:
      - image: maven:3.6-jdk-8

jobs:
  first:
    executor: openjdk8
    steps:
      - run: echo "only for tags"
  second:
    executor: openjdk8
    steps:
      - run: echo "second job"

workflows:
  welcome:
    jobs:
      - first:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
      - second
